site_name: OCI Registry As Storage
site_url: https://oras.land/
site_description: Tools and libraries to enable leveraging OCI registries for arbitrary artifacts
site_author: The ORAS Authors
repo_url: https://github.com/oras-project/oras-www
copyright: Copyright &copy; 2021 The ORAS Authors
extra_css:
  - assets/stylesheets/extra.css
theme:
  name: material
  logo: assets/images/oras.png
