site_name: OCI Registry As Storage
site_url: https://oras.land/
site_description: Tools and libraries to enable leveraging OCI registries for arbitrary artifacts
site_author: The ORAS Maintainers
repo_url: https://github.com/oras-project/oras-www
