site_name: OCI Registry As Storage
site_url: https://oras.land/
site_description: Tools and libraries to enable leveraging OCI registries for arbitrary artifacts
site_author: The ORAS Authors
repo_url: https://github.com/oras-project/oras
repo_name: oras-project/oras
edit_uri: ""
copyright: Copyright &copy; 2021 The ORAS Authors
extra_css:
  - assets/stylesheets/extra.css
plugins:
  - search
  - git-revision-date-localized
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/orasproject
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
theme:
  name: material
  logo: assets/images/oras.png
  favicon: assets/favicon.ico
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
